GET https://api.regulations.gov/v4/comments?filter[commentOnId]=090000648478e39d&sort=postedDate&page[number]=1&page[size]=50
X-Api-Key: 5F20SbTVakeYfU9i5gX1dxx96sw4KELUQxAHhcHa

###

GET https://api.regulations.gov/v4/comments?page[number]=2&page[size]=50
X-Api-Key: 5F20SbTVakeYfU9i5gX1dxx96sw4KELUQxAHhcHa

###

GET https://api.regulations.gov/v4/comments/CDC-2020-0087-1642
X-Api-Key: 5F20SbTVakeYfU9i5gX1dxx96sw4KELUQxAHhcHa

###

GET https://api.regulations.gov/v4/dockets/CDC-2020-0087
X-Api-Key: 5F20SbTVakeYfU9i5gX1dxx96sw4KELUQxAHhcHa

###

GET https://api.regulations.gov/v4/documents/CDC-2020-0087-0001
X-Api-Key: 5F20SbTVakeYfU9i5gX1dxx96sw4KELUQxAHhcHa


data: {
  attributes: {
    category: null
    city: "Bellingham"
    comment: "The cruise ship environment, based on the evidence we have so far, facilitates massive spread of COVID-19. Community healthcare systems are already overburdened by the pandemic. Are we seriously considering sanctioning several super-spreader events a week? No cruises until a vaccine!"
    commentOnDocumentId: "CDC-2020-0087-0001"
    country: "United States"
    email: "jay@portal.org"
    files: []
    firstName: "Jay"
    lastName: "Cheroske"
    numItemsReceived: null
    organization: null
    organizationType: null
    phone: ""
    recaptchaResponse: "03AGdBq27vbHnjlDBGbrr2pX40Z0ullKlJTiLSUwEy9vmArDJWhxunIZ78OAQJ3NY4YRunbVldx5Nzba9U6zvQS16TWUxFJWuSrP5riSUcQZChRcsSdbdXHMJUIw7GjzIHLNo8Yjms0Gwjw8OK5sij1TrjkVTXsO0zJcIHz-AUbQ6zEYgpKHDOsT_3x1to3Lc7gN7N-VDUmOy0YXYmhuD1Q55bjh6y8eONGsaB9-S5A2K5u0y7MJi06Q6aESVs0BcXWgjPpwahSCJeKlS_AnrTBphM5mmPkhdSaj72SA7TNuhHU2sTK5XbltLoEYHkqfww3IhLTSpAIOarSrY2tSlqNENPZLYIxkb_J5s_xrtjGUJY_JSHUv-teIl8hx4KHDicjdSKfoLcGF5ghX3Qm19arIIp1S7ETBBkQYMB4Li-IZ64TG9Xwi0qieg"
    receiveDate: null
    sendEmailReceipt: false
    stateProvinceRegion: "WA"
    submissionKey: "kf4-lasa-g7iy"
    submissionType: "WEB"
    submitterRep: null
    submitterType: "INDIVIDUAL"
    zip: "98225"
  }
  type: "comments"
}
